databases:
  - name: learnalgorithmic-db
    plan: free
    databaseName: learnalgorithmic
    user: learnalgorithmic

services:
  - type: web
    name: learnalgorithmic
    plan: free
    runtime: python
    rootDir: LearnAlgorithmic/backend
    buildCommand: ./build.sh
    startCommand: gunicorn learnalgorithmic.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: learnalgorithmic-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
